version: '3'
services:
  db:
    image: postgres:10.4-alpine
    env_file: .env
    networks:
      - internal_network
    volumes:
      - "pg_data:/var/lib/postgresql/data"
      - ".:/app"
  main:
    build: ./docker
    image: trasina/base
    env_file: .env
    networks:
      - default
      - internal_network
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "ruby_bundle:/usr/local/bundle"
      - "~/.ssh/id_rsa:/root/.ssh/id_rsa"
      - "./docker/nginx.conf.development:/etc/nginx/conf.d/default.conf"

networks:
  internal_network:
    internal: true
  default:
    external:
      name: default-network

volumes:
  pg_data:
  ruby_bundle:
