version: '3'
services:
  main:
    build: ./docker
    image: trasina/base
    env_file: .env.development
    networks:
      - default
      - internal_network
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "ruby_bundle:/usr/local/bundle"
      - "~/.ssh/id_rsa:/root/.ssh/id_rsa"
      - "./docker/nginx.conf.development:/etc/nginx/conf.d/default.conf"

networks:
  internal_network:
    internal: true
  default:
    external:
      name: default-network

volumes:
  ruby_bundle:
